sonar.projectKey=java-app
sonar.projectName=Java Application
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.host.url=http://192.168.56.15:9000
sonar.login=sqa_7432d0f4368379b584227fc54bca56ef236c58cf
